config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  resources :projects
  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services

    root to: "users#index"
  end
  get "/privacy", to: "home#privacy"
  get "/terms", to: "home#terms"
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.haml
%footer.footer.text-muted.bg-dark
  .container
    %span
      ©#{Date.today.year} Andrew Mason
    %ul.list-inline.mb-0.float-right
      %li.list-inline-item.mr-3
        = link_to "Terms", terms_path, class: "text-muted"
      %li.list-inline-item.mr-3
        = link_to "Privacy", privacy_path, class: "text-muted"

app/views/shared/_head.html.haml
%title= Rails.configuration.application_name
%meta{:charset => "utf-8"}/
%meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
= csrf_meta_tags
= csp_meta_tag
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

app/views/shared/_navbar.html.haml
- if user_masquerade?
  .alert.alert-warning.text-center
    You're logged in as
    %b
      = current_user.name
      (#{current_user.email})
    = link_to back_masquerade_path(current_user) do
      = icon("fas", "times")
      Logout
%nav.navbar.navbar-expand-md.navbar-dark.bg-dark
  .container
    = link_to Rails.configuration.application_name, root_path, class: "navbar-brand"
    %button.navbar-toggler{"aria-controls" => "navbarsExample04", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarMain", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarMain.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto.mt-2.mt-md-0
      %ul.navbar-nav
        %li.nav-item= link_to "What's New", announcements_path, class: "nav-link #{unread_announcements(current_user)}"
        %li.nav-item= link_to "Projects", projects_path, class: "nav-link"
        - if user_signed_in?
          %li.nav-item
            = link_to notifications_path, class: "nav-link" do
              %span
                %i.fa.fa-flag-o{"aria-hidden" => "true"}
          %li.nav-item.dropdown
            = link_to "#", id: "navbar-dropdown", class: "nav-link dropdown-toggle", data: { target: "nav-account-dropdown", toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do
              = image_tag gravatar_image_url(current_user.email, size: 40), height: 20, width: 20, class: "rounded"
            #nav-account-dropdown.dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbar-dropdown"}
              - if current_user.admin?
                = link_to "Admin Area", admin_root_path, class: "dropdown-item"
              = link_to "Settings", edit_user_registration_path, class: "dropdown-item"
              .dropdown-divider
              = link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item"
        - else
          %li.nav-item= link_to "Sign Up", new_user_registration_path, class: "nav-link"
          %li.nav-item= link_to "Login", new_user_session_path, class: "nav-link"

app/views/shared/_notices.html.haml
- flash.each do |msg_type, message|
  %div{class: "alert #{bootstrap_class_for(msg_type)}"}
    .container
      %button.close{"data-dismiss" => "alert"}
        %span ×
      = message